openai_api_key = "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"
tavily_api_key = "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"
perplexity_api_key = "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"
